version: '3.8'

services:
  shop_documentation:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs_shop
    command: serve --dev-addr=0.0.0.0:8010 --watch-theme
    restart: unless-stopped
    ports:
      - "1234:8010"
    volumes:
      - ./documentation:/docs:ro

  shop_local_database:
    image: postgres:16-alpine
    container_name: shop_local_database
    hostname: shop_local_database
    restart: always
    ports:
      - "2233:5432"
    volumes:
      - postgres_datastorage:/var/lib/postgresql/data
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  postgres_datastorage:
    external: false
