version: '3.8'

services:
  shop_documentation:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs_shop
    command: serve --dev-addr=0.0.0.0:8010 --watch-theme
    restart: unless-stopped
    ports:
      - "1234:8010"
    volumes:
      - ./documentation:/docs:ro

  shop_local_database:
    image: postgres:16-alpine
    container_name: shop_local_database
    hostname: shop_local_database
    restart: always
    env_file:
      - .env
    ports:
      - "2233:${POSTGRES_PORT}"
    volumes:
      - postgres_datastorage:/var/lib/postgresql/data
    networks:
      - main_network

  shop_backend_api:
    build:
      dockerfile: Dockerfile
      context: ./backend_api
    container_name: shop_backend_api
    restart: always
    env_file:
      - .env
    ports:
      - "0987:9999"
    command: |
      sh -c "
      uvicorn main:app --port=9999 --host=0.0.0.0 --reload
      "

networks:
  main_network:
    driver: bridge

volumes:
  postgres_datastorage:
    external: false
