services:
  shop_documentation:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs_shop
    command: serve --dev-addr=0.0.0.0:8010 --watch-theme
    restart: unless-stopped
    ports:
      - "1122:8010"
    volumes:
      - ./documentation:/docs:ro

  shop_local_database:
    image: postgres:16-alpine
    container_name: shop_local_database
    hostname: shop_local_database
    restart: always
    env_file:
      - .env
    ports:
      - "2233:${POSTGRES_PORT}"
    volumes:
      - postgres_datastorage:/var/lib/postgresql/data
    networks:
      - main_network

  shop_backend_api:
    build:
      dockerfile: Dockerfile
      context: ./backend_api
    container_name: shop_backend_api
    hostname: shop_backend_api
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend_api/app:/app
    ports:
      - "1234:9999"
    command: |
      sh -c "
      alembic upgrade head && \
      uvicorn main:app --port=9999 --host=0.0.0.0 --reload
      "
    networks:
      - main_network

  nginx_4:
    image: nginx:alpine
    container_name: nginx_4
    restart: always
    ports:
      - "80:80"
    networks:
      - main_network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  shop_frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: shop_frontend
    hostname: shop_frontend
    restart: always
    env_file:
      - .env
    volumes:
      - ./frontend/app:/app
    ports:
      - "12345:12345"
    command: |
      sh -c "
      uvicorn main:app --port=12345 --host=0.0.0.0 --reload
      "
    networks:
      - main_network

networks:
  main_network:
    driver: bridge

volumes:
  postgres_datastorage:
    external: false
