version: '3.8'

services:
  shop_documentation:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs_shop
    command: serve --dev -addr=0.0.0.0:8010 --watch-theme
    restart: unless-stopped
    ports:
      - '8010:8111'