"""add product

Revision ID: f5790fbcefb2
Revises: 3c1600367c54
Create Date: 2025-08-12 11:02:55.693343

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f5790fbcefb2"
down_revision: Union[str, Sequence[str], None] = "3c1600367c54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("uuid_data", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("main_image", sa.String(), nullable=False),
        sa.Column("images", postgresql.ARRAY(sa.String()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_products_description"), "products", ["description"], unique=False
    )
    op.create_index(op.f("ix_products_title"), "products", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_title"), table_name="products")
    op.drop_index(op.f("ix_products_description"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
